---
apiVersion: v1
kind: Namespace
metadata:
  name: f5-lb
  
---
apiVersion: v1
kind: Namespace
metadata:
  name: nat46
  annotations:
    k8s.ovn.org/hybrid-overlay-external-gw: 192.168.15.100
    k8s.ovn.org/hybrid-overlay-vtep: 192.168.222.152          
